# coding: utf-8

# flake8: noqa

"""
    mailsac API Specification

    ## About the API  The Mailsac API allows for interacting with Mailsac services, including checking email, email validations, setting up forwarding addresses, receiving web socket email messages, and sending outbound mail.  [**Get a free API key**](https://mailsac.com/api-keys)  Test the Mailsac API online:  * [**Swagger UI Explorer** &rarr;](https://mailsac.com/docs/swagger)  **Base API Endpoint**:  * `https://mailsac.com/api/` * _All API documentation is relative to this endpoint._  **OpenAPI Spec**:  * [Download JSON](https://mailsac.com/openapi.json) * [Download YAML](https://mailsac.com/openapi.yml)   ### Support and Resources  * [npm Node.js and Browser library - @mailsac/api](https://www.npmjs.com/package/@mailsac/api) * [Full Documentation and Guides](https://docs.mailsac.com) * [Community Support and Discussion Forums](https://forum.mailsac.com/forums/) * [Web socket example in Node.js - ruffrey](https://github.com/ruffrey/mailsac-node-websocket-example)  Paid Email Support, Pre-Sales    > support@team.mailsac.com  [Terms of Service](https://docs.mailsac.com/en/latest/about/terms_of_service.html)  [Privacy Policy](https://docs.mailsac.com/en/latest/about/privacy_policy.html)   # noqa: E501

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from client.api.account_api import AccountApi
from client.api.addresses_api import AddressesApi
from client.api.attachments_api import AttachmentsApi
from client.api.domains_api import DomainsApi
from client.api.messages_api import MessagesApi
from client.api.web_sockets_api import WebSocketsApi
from client.api.webhooks_api import WebhooksApi
from client.api.email_validation_api import EmailValidationApi
from client.api.message_stats_api import MessageStatsApi
# import ApiClient
from client.api_client import ApiClient
from client.configuration import Configuration
# import models into sdk package
from client.models.all_of_email_message_web_socket_frame_email import AllOfEmailMessageWebSocketFrameEmail
from client.models.attachment_identifier import AttachmentIdentifier
from client.models.attachment_meta import AttachmentMeta
from client.models.byte_encoding import ByteEncoding
from client.models.common_attachments import CommonAttachments
from client.models.current_user_info import CurrentUserInfo
from client.models.current_user_stats import CurrentUserStats
from client.models.domain import Domain
from client.models.domain_string import DomainString
from client.models.domains_list import DomainsList
from client.models.email_address import EmailAddress
from client.models.email_address_availability import EmailAddressAvailability
from client.models.email_address_integrity import EmailAddressIntegrity
from client.models.email_address_integrity_list import EmailAddressIntegrityList
from client.models.email_address_list import EmailAddressList
from client.models.email_attachment import EmailAttachment
from client.models.email_attachment_list import EmailAttachmentList
from client.models.email_message import EmailMessage
from client.models.email_message_body_props import EmailMessageBodyProps
from client.models.email_message_list import EmailMessageList
from client.models.email_message_short import EmailMessageShort
from client.models.email_message_web_socket_frame import EmailMessageWebSocketFrame
from client.models.email_message_webhook import EmailMessageWebhook
from client.models.email_recipient import EmailRecipient
from client.models.email_string import EmailString
from client.models.email_string_list import EmailStringList
from client.models.email_subject import EmailSubject
from client.models.error_response_body import ErrorResponseBody
from client.models.inline_response200 import InlineResponse200
from client.models.inline_response2001 import InlineResponse2001
from client.models.inline_response20010 import InlineResponse20010
from client.models.inline_response20011 import InlineResponse20011
from client.models.inline_response2002 import InlineResponse2002
from client.models.inline_response2003 import InlineResponse2003
from client.models.inline_response2004 import InlineResponse2004
from client.models.inline_response2005 import InlineResponse2005
from client.models.inline_response2006 import InlineResponse2006
from client.models.inline_response2007 import InlineResponse2007
from client.models.inline_response2008 import InlineResponse2008
from client.models.inline_response2009 import InlineResponse2009
from client.models.limit import Limit
from client.models.md5sum import Md5sum
from client.models.message_folder import MessageFolder
from client.models.message_headers import MessageHeaders
from client.models.message_id import MessageId
from client.models.message_label import MessageLabel
from client.models.message_labels import MessageLabels
from client.models.model_date import ModelDate
from client.models.not_enough_credits_response import NotEnoughCreditsResponse
from client.models.privateaddressesbulk_body import PrivateaddressesbulkBody
from client.models.read_boolean import ReadBoolean
from client.models.received_headers import ReceivedHeaders
from client.models.received_headers_list import ReceivedHeadersList
from client.models.send_message import SendMessage
from client.models.send_message_from import SendMessageFrom
from client.models.send_message_to import SendMessageTo
from client.models.skip import Skip
from client.models.too_many_recipients_response import TooManyRecipientsResponse
from client.models.update_private_address_forwarding import UpdatePrivateAddressForwarding
from client.models.validations_addresses_body import ValidationsAddressesBody
