# coding: utf-8

"""
    mailsac API Specification

    ## About the API  The Mailsac API allows for interacting with Mailsac services, including checking email, email validations, setting up forwarding addresses, receiving web socket email messages, and sending outbound mail.  [**Get a free API key**](https://mailsac.com/api-keys)  Test the Mailsac API online:  * [**Swagger UI Explorer** &rarr;](https://mailsac.com/docs/swagger)  **Base API Endpoint**:  * `https://mailsac.com/api/` * _All API documentation is relative to this endpoint._  **OpenAPI Spec**:  * [Download JSON](https://mailsac.com/openapi.json) * [Download YAML](https://mailsac.com/openapi.yml)   ### Support and Resources  * [npm Node.js and Browser library - @mailsac/api](https://www.npmjs.com/package/@mailsac/api) * [Full Documentation and Guides](https://docs.mailsac.com) * [Community Support and Discussion Forums](https://forum.mailsac.com/forums/) * [Web socket example in Node.js - ruffrey](https://github.com/ruffrey/mailsac-node-websocket-example)  Paid Email Support, Pre-Sales    > support@team.mailsac.com  [Terms of Service](https://docs.mailsac.com/en/latest/about/terms_of_service.html)  [Privacy Policy](https://docs.mailsac.com/en/latest/about/privacy_policy.html)   # noqa: E501

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import client
from client.api.messages_api import MessagesApi  # noqa: E501
from client.rest import ApiException


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self):
        self.api = MessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_message_label(self):
        """Test case for add_message_label

        Add a label to a message  # noqa: E501
        """
        pass

    def test_count_messages(self):
        """Test case for count_messages

        Count messages for an email inbox  # noqa: E501
        """
        pass

    def test_delete_all_domain_messages(self):
        """Test case for delete_all_domain_messages

        Delete all messages in a domain  # noqa: E501
        """
        pass

    def test_delete_all_messages(self):
        """Test case for delete_all_messages

        Delete all messages for an email inbox  # noqa: E501
        """
        pass

    def test_delete_message(self):
        """Test case for delete_message

        Delete an email message  # noqa: E501
        """
        pass

    def test_delete_message_label(self):
        """Test case for delete_message_label

        Remove a label from a message  # noqa: E501
        """
        pass

    def test_filter_inbox_messages(self):
        """Test case for filter_inbox_messages

        Filter messages in account by to, from, and/or subject  # noqa: E501
        """
        pass

    def test_get_body_dirty(self):
        """Test case for get_body_dirty

        Get message HTML body (dirty)  # noqa: E501
        """
        pass

    def test_get_body_plain_text(self):
        """Test case for get_body_plain_text

        Get message plaintext  # noqa: E501
        """
        pass

    def test_get_body_sanitized(self):
        """Test case for get_body_sanitized

        Get the message HTML body (sanitized)  # noqa: E501
        """
        pass

    def test_get_full_raw_message(self):
        """Test case for get_full_raw_message

        Get original SMTP message  # noqa: E501
        """
        pass

    def test_get_headers(self):
        """Test case for get_headers

        Get parsed message headers  # noqa: E501
        """
        pass

    def test_get_message_metadata(self):
        """Test case for get_message_metadata

        Get email message metadata  # noqa: E501
        """
        pass

    def test_list_domain_messages(self):
        """Test case for list_domain_messages

        List messages for an domain  # noqa: E501
        """
        pass

    def test_list_inbox_messages(self):
        """Test case for list_inbox_messages

        Get all account messages paginated  # noqa: E501
        """
        pass

    def test_list_messages(self):
        """Test case for list_messages

        List messages for an email inbox  # noqa: E501
        """
        pass

    def test_list_starred_messages(self):
        """Test case for list_starred_messages

        List starred (saved) messages on the account  # noqa: E501
        """
        pass

    def test_search_inbox_messages(self):
        """Test case for search_inbox_messages

        Search messages by to, from, and subject  # noqa: E501
        """
        pass

    def test_set_message_folder(self):
        """Test case for set_message_folder

        Move a message into a folder  # noqa: E501
        """
        pass

    def test_set_message_read_status(self):
        """Test case for set_message_read_status

        Set message read/unread status  # noqa: E501
        """
        pass

    def test_toggle_message_star(self):
        """Test case for toggle_message_star

        Star (save) a message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
