# coding: utf-8

"""
    mailsac API Specification

    ## About the API  The Mailsac API allows for interacting with Mailsac services, including checking email, email validations, setting up forwarding addresses, receiving web socket email messages, and sending outbound mail.  [**Get a free API key**](https://mailsac.com/api-keys)  Test the Mailsac API online:  * [**Swagger UI Explorer** &rarr;](https://mailsac.com/docs/swagger)  **Base API Endpoint**:  * `https://mailsac.com/api/` * _All API documentation is relative to this endpoint._  **OpenAPI Spec**:  * [Download JSON](https://mailsac.com/openapi.json) * [Download YAML](https://mailsac.com/openapi.yml)   ### Support and Resources  * [npm Node.js and Browser library - @mailsac/api](https://www.npmjs.com/package/@mailsac/api) * [Full Documentation and Guides](https://docs.mailsac.com) * [Community Support and Discussion Forums](https://forum.mailsac.com/forums/) * [Web socket example in Node.js - ruffrey](https://github.com/ruffrey/mailsac-node-websocket-example)  Paid Email Support, Pre-Sales    > support@team.mailsac.com  [Terms of Service](https://docs.mailsac.com/en/latest/about/terms_of_service.html)  [Privacy Policy](https://docs.mailsac.com/en/latest/about/privacy_policy.html)   # noqa: E501

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EmailAddressAvailability(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'available': 'bool',
        'email': 'str',
        'owned': 'bool'
    }

    attribute_map = {
        'available': 'available',
        'email': 'email',
        'owned': 'owned'
    }

    def __init__(self, available=None, email=None, owned=None):  # noqa: E501
        """EmailAddressAvailability - a model defined in Swagger"""  # noqa: E501
        self._available = None
        self._email = None
        self._owned = None
        self.discriminator = None
        if available is not None:
            self.available = available
        if email is not None:
            self.email = email
        if owned is not None:
            self.owned = owned

    @property
    def available(self):
        """Gets the available of this EmailAddressAvailability.  # noqa: E501

        Indicates if the address is available to be reserved  # noqa: E501

        :return: The available of this EmailAddressAvailability.  # noqa: E501
        :rtype: bool
        """
        return self._available

    @available.setter
    def available(self, available):
        """Sets the available of this EmailAddressAvailability.

        Indicates if the address is available to be reserved  # noqa: E501

        :param available: The available of this EmailAddressAvailability.  # noqa: E501
        :type: bool
        """

        self._available = available

    @property
    def email(self):
        """Gets the email of this EmailAddressAvailability.  # noqa: E501

        email address  # noqa: E501

        :return: The email of this EmailAddressAvailability.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this EmailAddressAvailability.

        email address  # noqa: E501

        :param email: The email of this EmailAddressAvailability.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def owned(self):
        """Gets the owned of this EmailAddressAvailability.  # noqa: E501

        Indicates if the address is owned by an account, but not by whom.  # noqa: E501

        :return: The owned of this EmailAddressAvailability.  # noqa: E501
        :rtype: bool
        """
        return self._owned

    @owned.setter
    def owned(self, owned):
        """Sets the owned of this EmailAddressAvailability.

        Indicates if the address is owned by an account, but not by whom.  # noqa: E501

        :param owned: The owned of this EmailAddressAvailability.  # noqa: E501
        :type: bool
        """

        self._owned = owned

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EmailAddressAvailability, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmailAddressAvailability):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
