# coding: utf-8

"""
    mailsac API Specification

    ## About the API  The Mailsac API allows for interacting with Mailsac services, including checking email, email validations, setting up forwarding addresses, receiving web socket email messages, and sending outbound mail.  [**Get a free API key**](https://mailsac.com/api-keys)  Test the Mailsac API online:  * [**Swagger UI Explorer** &rarr;](https://mailsac.com/docs/swagger)  **Base API Endpoint**:  * `https://mailsac.com/api/` * _All API documentation is relative to this endpoint._  **OpenAPI Spec**:  * [Download JSON](https://mailsac.com/openapi.json) * [Download YAML](https://mailsac.com/openapi.yml)   ### Support and Resources  * [npm Node.js and Browser library - @mailsac/api](https://www.npmjs.com/package/@mailsac/api) * [Full Documentation and Guides](https://docs.mailsac.com) * [Community Support and Discussion Forums](https://forum.mailsac.com/forums/) * [Web socket example in Node.js - ruffrey](https://github.com/ruffrey/mailsac-node-websocket-example)  Paid Email Support, Pre-Sales    > support@team.mailsac.com  [Terms of Service](https://docs.mailsac.com/en/latest/about/terms_of_service.html)  [Privacy Policy](https://docs.mailsac.com/en/latest/about/privacy_policy.html)   # noqa: E501

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SendMessage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'to': 'SendMessageTo',
        '_from': 'SendMessageFrom',
        'subject': 'EmailSubject',
        'text': 'str',
        'html': 'str',
        'attachments': 'EmailAttachmentList',
        'received': 'list[ReceivedHeadersList]',
        'raw': 'str'
    }

    attribute_map = {
        'to': 'to',
        '_from': 'from',
        'subject': 'subject',
        'text': 'text',
        'html': 'html',
        'attachments': 'attachments',
        'received': 'received',
        'raw': 'raw'
    }

    def __init__(self, to=None, _from=None, subject=None, text=None, html=None, attachments=None, received=None, raw=None):  # noqa: E501
        """SendMessage - a model defined in Swagger"""  # noqa: E501
        self._to = None
        self.__from = None
        self._subject = None
        self._text = None
        self._html = None
        self._attachments = None
        self._received = None
        self._raw = None
        self.discriminator = None
        self.to = to
        self._from = _from
        self.subject = subject
        self.text = text
        self.html = html
        if attachments is not None:
            self.attachments = attachments
        if received is not None:
            self.received = received
        if raw is not None:
            self.raw = raw

    @property
    def to(self):
        """Gets the to of this SendMessage.  # noqa: E501


        :return: The to of this SendMessage.  # noqa: E501
        :rtype: SendMessageTo
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this SendMessage.


        :param to: The to of this SendMessage.  # noqa: E501
        :type: SendMessageTo
        """
        if to is None:
            raise ValueError("Invalid value for `to`, must not be `None`")  # noqa: E501

        self._to = to

    @property
    def _from(self):
        """Gets the _from of this SendMessage.  # noqa: E501


        :return: The _from of this SendMessage.  # noqa: E501
        :rtype: SendMessageFrom
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this SendMessage.


        :param _from: The _from of this SendMessage.  # noqa: E501
        :type: SendMessageFrom
        """
        if _from is None:
            raise ValueError("Invalid value for `_from`, must not be `None`")  # noqa: E501

        self.__from = _from

    @property
    def subject(self):
        """Gets the subject of this SendMessage.  # noqa: E501


        :return: The subject of this SendMessage.  # noqa: E501
        :rtype: EmailSubject
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this SendMessage.


        :param subject: The subject of this SendMessage.  # noqa: E501
        :type: EmailSubject
        """
        if subject is None:
            raise ValueError("Invalid value for `subject`, must not be `None`")  # noqa: E501

        self._subject = subject

    @property
    def text(self):
        """Gets the text of this SendMessage.  # noqa: E501

        plaintext email contents  # noqa: E501

        :return: The text of this SendMessage.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this SendMessage.

        plaintext email contents  # noqa: E501

        :param text: The text of this SendMessage.  # noqa: E501
        :type: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def html(self):
        """Gets the html of this SendMessage.  # noqa: E501

        html email contents  # noqa: E501

        :return: The html of this SendMessage.  # noqa: E501
        :rtype: str
        """
        return self._html

    @html.setter
    def html(self, html):
        """Sets the html of this SendMessage.

        html email contents  # noqa: E501

        :param html: The html of this SendMessage.  # noqa: E501
        :type: str
        """
        if html is None:
            raise ValueError("Invalid value for `html`, must not be `None`")  # noqa: E501

        self._html = html

    @property
    def attachments(self):
        """Gets the attachments of this SendMessage.  # noqa: E501


        :return: The attachments of this SendMessage.  # noqa: E501
        :rtype: EmailAttachmentList
        """
        return self._attachments

    @attachments.setter
    def attachments(self, attachments):
        """Sets the attachments of this SendMessage.


        :param attachments: The attachments of this SendMessage.  # noqa: E501
        :type: EmailAttachmentList
        """

        self._attachments = attachments

    @property
    def received(self):
        """Gets the received of this SendMessage.  # noqa: E501


        :return: The received of this SendMessage.  # noqa: E501
        :rtype: list[ReceivedHeadersList]
        """
        return self._received

    @received.setter
    def received(self, received):
        """Sets the received of this SendMessage.


        :param received: The received of this SendMessage.  # noqa: E501
        :type: list[ReceivedHeadersList]
        """

        self._received = received

    @property
    def raw(self):
        """Gets the raw of this SendMessage.  # noqa: E501

        raw SMTP messsage overrides all other properties  # noqa: E501

        :return: The raw of this SendMessage.  # noqa: E501
        :rtype: str
        """
        return self._raw

    @raw.setter
    def raw(self, raw):
        """Sets the raw of this SendMessage.

        raw SMTP messsage overrides all other properties  # noqa: E501

        :param raw: The raw of this SendMessage.  # noqa: E501
        :type: str
        """

        self._raw = raw

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SendMessage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SendMessage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
